"""Add response_feedback table

Revision ID: c2c8bf1dc3b5
Revises: add_message_threading
Create Date: 2025-09-30 02:10:00.788732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2c8bf1dc3b5'
down_revision: Union[str, Sequence[str], None] = 'add_message_threading'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', name='feedbacktype'), nullable=False),
    sa.Column('feedback_category', sa.Enum('INCORRECT', 'INCOMPLETE', 'IRRELEVANT', 'UNCLEAR', 'SLOW', 'OTHER', name='feedbackcategory'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_feedback_conversation_id'), 'response_feedback', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_response_feedback_created_at'), 'response_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_response_feedback_feedback_type'), 'response_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_response_feedback_id'), 'response_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_response_feedback_message_id'), 'response_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_response_feedback_reviewed'), 'response_feedback', ['reviewed'], unique=False)
    op.create_index(op.f('ix_response_feedback_user_id'), 'response_feedback', ['user_id'], unique=False)
    # Don't drop spatial_ref_sys - it's part of PostGIS extension
    # op.drop_table('spatial_ref_sys')
    op.create_foreign_key(None, 'messages', 'messages', ['parent_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # Don't recreate spatial_ref_sys - it's part of PostGIS extension
    # op.create_table('spatial_ref_sys', ...)
    op.drop_index(op.f('ix_response_feedback_user_id'), table_name='response_feedback')
    op.drop_index(op.f('ix_response_feedback_reviewed'), table_name='response_feedback')
    op.drop_index(op.f('ix_response_feedback_message_id'), table_name='response_feedback')
    op.drop_index(op.f('ix_response_feedback_id'), table_name='response_feedback')
    op.drop_index(op.f('ix_response_feedback_feedback_type'), table_name='response_feedback')
    op.drop_index(op.f('ix_response_feedback_created_at'), table_name='response_feedback')
    op.drop_index(op.f('ix_response_feedback_conversation_id'), table_name='response_feedback')
    op.drop_table('response_feedback')
    # ### end Alembic commands ###
