"""
Part 2 of disease data - Colza, Orge, and Tournesol diseases
This file contains the remaining diseases to keep the main file under 300 lines
"""

# Remaining Colza diseases (8 more)
COLZA_DISEASES_PART2 = [
    {
        "name": "Cylindrosporiose",
        "scientific_name": "Pyrenopeziza brassicae",
        "common_names": ["Light leaf spot", "Taches claires"],
        "disease_type": "fungal",
        "pathogen_name": "Pyrenopeziza brassicae",
        "severity_level": "high",
        "eppo_code": "PYRNBR",
        "symptoms": ["taches_claires_feuilles", "déformation_siliques", "chute_feuilles"],
        "visual_indicators": ["taches_blanc_gris", "sporulation_blanche"],
        "favorable_conditions": {"humidity": "high", "temperature": "cool", "temperature_range": [10, 18]},
        "seasonal_occurrence": ["automne", "hiver", "printemps"],
        "susceptible_bbch_stages": [14, 15, 16, 30, 31, 32, 61, 65],
        "treatment_options": ["fongicide_triazole"],
        "prevention_methods": ["variétés_résistantes", "rotation_cultures"],
        "yield_impact": "10-30%"
    },
    {
        "name": "Alternariose",
        "scientific_name": "Alternaria brassicae",
        "common_names": ["Alternaria black spot", "Taches noires"],
        "disease_type": "fungal",
        "pathogen_name": "Alternaria brassicae",
        "severity_level": "moderate",
        "eppo_code": "ALTEBR",
        "symptoms": ["taches_noires_concentriques", "nécroses_feuilles", "siliques_tachées"],
        "visual_indicators": ["anneaux_concentriques", "taches_noires"],
        "favorable_conditions": {"humidity": "high", "temperature": "warm", "temperature_range": [20, 28]},
        "seasonal_occurrence": ["printemps", "été"],
        "susceptible_bbch_stages": [51, 55, 61, 65, 69, 71],
        "treatment_options": ["fongicide_iprodione"],
        "prevention_methods": ["semences_saines", "rotation_cultures"],
        "yield_impact": "5-20%"
    },
    {
        "name": "Mildiou du colza",
        "scientific_name": "Hyaloperonospora parasitica",
        "common_names": ["Downy mildew", "Mildiou"],
        "disease_type": "oomycete",
        "pathogen_name": "Hyaloperonospora parasitica",
        "severity_level": "moderate",
        "eppo_code": "PEROPA",
        "symptoms": ["taches_jaunes_dessus", "duvet_blanc_dessous", "déformation_feuilles"],
        "visual_indicators": ["sporulation_blanche_face_inférieure"],
        "favorable_conditions": {"humidity": "very_high", "temperature": "cool", "temperature_range": [10, 18]},
        "seasonal_occurrence": ["automne", "hiver"],
        "susceptible_bbch_stages": [10, 11, 12, 13, 14, 15, 16],
        "treatment_options": ["fongicide_métalaxyl"],
        "prevention_methods": ["semences_traitées", "drainage"],
        "yield_impact": "5-15%"
    },
    {
        "name": "Verticilliose",
        "scientific_name": "Verticillium longisporum",
        "common_names": ["Verticillium wilt", "Flétrissement verticillien"],
        "disease_type": "fungal",
        "pathogen_name": "Verticillium longisporum",
        "severity_level": "high",
        "eppo_code": "VERTLO",
        "symptoms": ["flétrissement_unilatéral", "jaunissement_feuilles", "brunissement_vasculaire"],
        "visual_indicators": ["décoloration_vasculaire", "flétrissement_asymétrique"],
        "favorable_conditions": {"temperature": "moderate", "sol_contaminé": True},
        "seasonal_occurrence": ["printemps", "été"],
        "susceptible_bbch_stages": [30, 31, 32, 37, 39, 51, 55, 61],
        "treatment_options": ["pas_traitement_curatif"],
        "prevention_methods": ["rotation_longue", "variétés_tolérantes"],
        "yield_impact": "10-40%"
    },
    {
        "name": "Hernie du chou",
        "scientific_name": "Plasmodiophora brassicae",
        "common_names": ["Clubroot", "Hernie"],
        "disease_type": "protist",
        "pathogen_name": "Plasmodiophora brassicae",
        "severity_level": "critical",
        "eppo_code": "PLABRA",
        "symptoms": ["galles_racines", "flétrissement", "nanisme", "jaunissement"],
        "visual_indicators": ["racines_déformées_gonflées", "galles_racinaires"],
        "favorable_conditions": {"pH": "acide", "sol_humide": True, "temperature_range": [18, 25]},
        "seasonal_occurrence": ["toute_année"],
        "susceptible_bbch_stages": [0, 1, 9, 10, 11, 12, 13, 14],
        "treatment_options": ["chaulage", "drainage"],
        "prevention_methods": ["rotation_longue", "variétés_résistantes", "chaulage_préventif"],
        "yield_impact": "20-100%"
    },
    {
        "name": "Oïdium du colza",
        "scientific_name": "Erysiphe cruciferarum",
        "common_names": ["Powdery mildew", "Blanc"],
        "disease_type": "fungal",
        "pathogen_name": "Erysiphe cruciferarum",
        "severity_level": "low",
        "eppo_code": "ERYSCH",
        "symptoms": ["poudre_blanche_feuilles", "taches_blanches"],
        "visual_indicators": ["mycélium_blanc_superficiel"],
        "favorable_conditions": {"humidity": "moderate", "temperature": "moderate"},
        "seasonal_occurrence": ["printemps", "été"],
        "susceptible_bbch_stages": [30, 31, 32, 37, 39, 51, 55],
        "treatment_options": ["fongicide_soufre"],
        "prevention_methods": ["aération", "densité_réduite"],
        "yield_impact": "1-5%"
    },
    {
        "name": "Botrytis du colza",
        "scientific_name": "Botrytis cinerea",
        "common_names": ["Gray mold", "Pourriture grise"],
        "disease_type": "fungal",
        "pathogen_name": "Botrytis cinerea",
        "severity_level": "moderate",
        "eppo_code": "BOTRCI",
        "symptoms": ["pourriture_grise_siliques", "moisissure_grise"],
        "visual_indicators": ["mycélium_gris", "sporulation_grise"],
        "favorable_conditions": {"humidity": "very_high", "temperature": "moderate"},
        "seasonal_occurrence": ["printemps", "été"],
        "susceptible_bbch_stages": [61, 65, 69, 71, 75],
        "treatment_options": ["fongicide_iprodione"],
        "prevention_methods": ["aération", "éviter_densité_excessive"],
        "yield_impact": "5-15%"
    },
    {
        "name": "Rhizoctone brun",
        "scientific_name": "Rhizoctonia solani",
        "common_names": ["Rhizoctonia root rot", "Rhizoctone"],
        "disease_type": "fungal",
        "pathogen_name": "Rhizoctonia solani",
        "severity_level": "moderate",
        "eppo_code": "RHIZSO",
        "symptoms": ["pourriture_collet", "fonte_semis", "lésions_brunes_base"],
        "visual_indicators": ["nécroses_brunes_collet", "mycélium_brun"],
        "favorable_conditions": {"sol_humide": True, "temperature": "moderate"},
        "seasonal_occurrence": ["automne", "printemps"],
        "susceptible_bbch_stages": [0, 1, 9, 10, 11, 12, 13],
        "treatment_options": ["traitement_semences"],
        "prevention_methods": ["drainage", "rotation_cultures"],
        "yield_impact": "5-20%"
    }
]

# Orge diseases (10 diseases)
ORGE_DISEASES = [
    {
        "name": "Rhynchosporiose de l'orge",
        "scientific_name": "Rhynchosporium commune",
        "common_names": ["Scald", "Échaudure"],
        "disease_type": "fungal",
        "pathogen_name": "Rhynchosporium commune",
        "severity_level": "high",
        "eppo_code": "RHYNSE",
        "symptoms": ["taches_gris_bleu", "halo_brun", "nécroses_feuilles"],
        "visual_indicators": ["lésions_ovales_centre_gris"],
        "favorable_conditions": {"humidity": "high", "temperature": "cool", "temperature_range": [10, 20]},
        "seasonal_occurrence": ["automne", "hiver", "printemps"],
        "susceptible_bbch_stages": [21, 22, 23, 29, 30, 31, 32, 37],
        "treatment_options": ["fongicide_triazole", "fongicide_strobilurine"],
        "prevention_methods": ["variétés_résistantes", "rotation_cultures"],
        "yield_impact": "10-40%"
    },
    {
        "name": "Helminthosporiose de l'orge",
        "scientific_name": "Pyrenophora teres",
        "common_names": ["Net blotch", "Rayure réticulée"],
        "disease_type": "fungal",
        "pathogen_name": "Pyrenophora teres",
        "severity_level": "high",
        "eppo_code": "PYRNTE",
        "symptoms": ["stries_brunes_réticulées", "nécroses_feuilles"],
        "visual_indicators": ["motif_réticulé", "stries_longitudinales_transversales"],
        "favorable_conditions": {"humidity": "high", "temperature": "moderate", "temperature_range": [15, 25]},
        "seasonal_occurrence": ["printemps", "été"],
        "susceptible_bbch_stages": [21, 22, 23, 29, 30, 31, 32, 37, 39],
        "treatment_options": ["fongicide_triazole", "fongicide_strobilurine"],
        "prevention_methods": ["variétés_résistantes", "labour", "rotation_cultures"],
        "yield_impact": "15-40%"
    },
    {
        "name": "Oïdium de l'orge",
        "scientific_name": "Blumeria graminis f. sp. hordei",
        "common_names": ["Powdery mildew", "Blanc"],
        "disease_type": "fungal",
        "pathogen_name": "Blumeria graminis",
        "severity_level": "moderate",
        "eppo_code": "ERYSGH",
        "symptoms": ["poudre_blanche_feuilles", "taches_blanches"],
        "visual_indicators": ["mycélium_blanc_superficiel", "feutrage_blanc"],
        "favorable_conditions": {"humidity": "moderate", "temperature": "cool", "temperature_range": [15, 22]},
        "seasonal_occurrence": ["printemps", "automne"],
        "susceptible_bbch_stages": [21, 22, 23, 29, 30, 31, 32],
        "treatment_options": ["fongicide_soufre", "fongicide_triazole"],
        "prevention_methods": ["variétés_résistantes", "densité_réduite"],
        "yield_impact": "5-20%"
    },
    {
        "name": "Rouille naine",
        "scientific_name": "Puccinia hordei",
        "common_names": ["Dwarf rust", "Leaf rust"],
        "disease_type": "fungal",
        "pathogen_name": "Puccinia hordei",
        "severity_level": "high",
        "eppo_code": "PUCCHN",
        "symptoms": ["pustules_brun_orangé", "feuilles_jaunies"],
        "visual_indicators": ["pustules_petites_dispersées", "poudre_orangée"],
        "favorable_conditions": {"humidity": "high", "temperature": "moderate", "temperature_range": [15, 22]},
        "seasonal_occurrence": ["printemps", "été"],
        "susceptible_bbch_stages": [30, 31, 32, 37, 39, 51, 55, 61],
        "treatment_options": ["fongicide_triazole"],
        "prevention_methods": ["variétés_résistantes", "élimination_résidus"],
        "yield_impact": "10-30%"
    },
    {
        "name": "Ramulariose",
        "scientific_name": "Ramularia collo-cygni",
        "common_names": ["Ramularia leaf spot", "Taches ramularia"],
        "disease_type": "fungal",
        "pathogen_name": "Ramularia collo-cygni",
        "severity_level": "moderate",
        "eppo_code": "RAMUCO",
        "symptoms": ["taches_brunes_rectangulaires", "halo_jaune", "nécroses"],
        "visual_indicators": ["lésions_brunes_bordure_foncée"],
        "favorable_conditions": {"humidity": "high", "temperature": "moderate", "temperature_range": [15, 20]},
        "seasonal_occurrence": ["printemps", "été"],
        "susceptible_bbch_stages": [51, 55, 61, 65, 69, 71],
        "treatment_options": ["fongicide_triazole", "fongicide_strobilurine"],
        "prevention_methods": ["variétés_tolérantes", "fongicide_préventif"],
        "yield_impact": "5-25%"
    },
    {
        "name": "Charbon nu de l'orge",
        "scientific_name": "Ustilago nuda",
        "common_names": ["Loose smut", "Charbon"],
        "disease_type": "fungal",
        "pathogen_name": "Ustilago nuda",
        "severity_level": "moderate",
        "eppo_code": "USTINU",
        "symptoms": ["épis_noirs", "spores_noires", "grains_détruits"],
        "visual_indicators": ["masse_spores_noires", "épis_transformés"],
        "favorable_conditions": {"temperature": "moderate", "infection_floraison": True},
        "seasonal_occurrence": ["été"],
        "susceptible_bbch_stages": [61, 65, 69],
        "treatment_options": ["traitement_semences_systémique"],
        "prevention_methods": ["semences_certifiées", "traitement_semences"],
        "yield_impact": "1-10%"
    },
    {
        "name": "Fusariose de l'épi d'orge",
        "scientific_name": "Fusarium graminearum",
        "common_names": ["Fusarium head blight", "FHB"],
        "disease_type": "fungal",
        "pathogen_name": "Fusarium graminearum",
        "severity_level": "high",
        "eppo_code": "FUSAGR",
        "symptoms": ["épis_blanchis", "grains_échaudés", "mycotoxines"],
        "visual_indicators": ["épis_décolorés", "mycélium_rose"],
        "favorable_conditions": {"humidity": "very_high", "temperature": "warm", "pluie_floraison": True, "temperature_range": [20, 30]},
        "seasonal_occurrence": ["été"],
        "susceptible_bbch_stages": [61, 65, 69],
        "treatment_options": ["fongicide_triazole_floraison"],
        "prevention_methods": ["rotation_cultures", "labour", "variétés_résistantes"],
        "yield_impact": "10-50%"
    },
    {
        "name": "Septoriose de l'orge",
        "scientific_name": "Septoria nodorum",
        "common_names": ["Septoria leaf blotch", "Septoriose"],
        "disease_type": "fungal",
        "pathogen_name": "Parastagonospora nodorum",
        "severity_level": "moderate",
        "eppo_code": "LEPTNO",
        "symptoms": ["taches_brunes_feuilles", "pycnides_noires"],
        "visual_indicators": ["lésions_brunes_pycnides"],
        "favorable_conditions": {"humidity": "high", "temperature": "moderate", "temperature_range": [15, 25]},
        "seasonal_occurrence": ["printemps", "été"],
        "susceptible_bbch_stages": [30, 31, 32, 37, 39, 51, 55],
        "treatment_options": ["fongicide_triazole"],
        "prevention_methods": ["rotation_cultures", "labour"],
        "yield_impact": "5-20%"
    },
    {
        "name": "Piétin-verse de l'orge",
        "scientific_name": "Oculimacula yallundae",
        "common_names": ["Eyespot", "Piétin"],
        "disease_type": "fungal",
        "pathogen_name": "Oculimacula yallundae",
        "severity_level": "moderate",
        "eppo_code": "PSDNYL",
        "symptoms": ["taches_oculaires_base_tige", "verse"],
        "visual_indicators": ["lésions_elliptiques_centre_blanc"],
        "favorable_conditions": {"humidity": "high", "temperature": "cool", "temperature_range": [5, 15]},
        "seasonal_occurrence": ["automne", "hiver", "printemps"],
        "susceptible_bbch_stages": [21, 22, 23, 29, 30, 31],
        "treatment_options": ["fongicide_prochloraze"],
        "prevention_methods": ["rotation_cultures", "labour"],
        "yield_impact": "5-30%"
    },
    {
        "name": "Mosaïque de l'orge",
        "scientific_name": "Barley yellow dwarf virus",
        "common_names": ["BYDV", "Jaunisse nanisante"],
        "disease_type": "viral",
        "pathogen_name": "Barley yellow dwarf virus",
        "severity_level": "high",
        "eppo_code": "BYDV00",
        "symptoms": ["jaunissement_feuilles", "nanisme", "rougissement"],
        "visual_indicators": ["feuilles_jaunes_rouges", "plantes_naines"],
        "favorable_conditions": {"vecteur": "pucerons", "temperature": "moderate"},
        "seasonal_occurrence": ["automne", "printemps"],
        "susceptible_bbch_stages": [10, 11, 12, 13, 21, 22, 23],
        "treatment_options": ["lutte_pucerons"],
        "prevention_methods": ["variétés_tolérantes", "lutte_vecteurs", "semis_tardif"],
        "yield_impact": "10-80%"
    }
]

# Tournesol diseases (10 diseases)
TOURNESOL_DISEASES = [
    {
        "name": "Mildiou du tournesol",
        "scientific_name": "Plasmopara halstedii",
        "common_names": ["Downy mildew", "Mildiou"],
        "disease_type": "oomycete",
        "pathogen_name": "Plasmopara halstedii",
        "severity_level": "critical",
        "eppo_code": "PLASHA",
        "symptoms": ["nanisme", "chlorose", "duvet_blanc_face_inférieure", "déformation"],
        "visual_indicators": ["sporulation_blanche", "plantes_chétives"],
        "favorable_conditions": {"sol_humide": True, "temperature": "cool", "temperature_range": [15, 20]},
        "seasonal_occurrence": ["printemps"],
        "susceptible_bbch_stages": [0, 1, 9, 10, 11, 12, 13, 14, 15],
        "treatment_options": ["traitement_semences", "fongicide_métalaxyl"],
        "prevention_methods": ["variétés_résistantes", "rotation_longue", "semences_traitées"],
        "yield_impact": "50-100%"
    },
    {
        "name": "Sclérotinia du tournesol",
        "scientific_name": "Sclerotinia sclerotiorum",
        "common_names": ["Sclerotinia head rot", "Pourriture blanche"],
        "disease_type": "fungal",
        "pathogen_name": "Sclerotinia sclerotiorum",
        "severity_level": "critical",
        "eppo_code": "SCLESC",
        "symptoms": ["pourriture_capitule", "pourriture_tige", "sclérotes_noirs"],
        "visual_indicators": ["mycélium_blanc", "sclérotes_noirs_internes"],
        "favorable_conditions": {"humidity": "very_high", "temperature": "moderate", "temperature_range": [15, 25]},
        "seasonal_occurrence": ["été"],
        "susceptible_bbch_stages": [61, 65, 69, 71, 75],
        "treatment_options": ["fongicide_floraison", "récolte_précoce"],
        "prevention_methods": ["rotation_longue", "densité_optimale", "drainage"],
        "yield_impact": "20-80%"
    },
    {
        "name": "Phomopsis",
        "scientific_name": "Diaporthe helianthi",
        "common_names": ["Phomopsis stem canker", "Chancre phomopsis"],
        "disease_type": "fungal",
        "pathogen_name": "Diaporthe helianthi",
        "severity_level": "high",
        "eppo_code": "DIAPH",
        "symptoms": ["chancres_tige", "taches_brunes_feuilles", "verse"],
        "visual_indicators": ["lésions_brunes_allongées_tige", "pycnides"],
        "favorable_conditions": {"humidity": "high", "temperature": "moderate", "temperature_range": [20, 25]},
        "seasonal_occurrence": ["été"],
        "susceptible_bbch_stages": [30, 31, 32, 37, 39, 51, 55, 61],
        "treatment_options": ["fongicide_triazole"],
        "prevention_methods": ["variétés_résistantes", "rotation_cultures", "labour"],
        "yield_impact": "10-40%"
    },
    {
        "name": "Alternariose du tournesol",
        "scientific_name": "Alternaria helianthi",
        "common_names": ["Alternaria leaf spot", "Taches alternaria"],
        "disease_type": "fungal",
        "pathogen_name": "Alternaria helianthi",
        "severity_level": "moderate",
        "eppo_code": "ALTEHE",
        "symptoms": ["taches_brunes_concentriques", "nécroses_feuilles"],
        "visual_indicators": ["anneaux_concentriques", "taches_noires"],
        "favorable_conditions": {"humidity": "high", "temperature": "warm", "temperature_range": [25, 30]},
        "seasonal_occurrence": ["été"],
        "susceptible_bbch_stages": [31, 32, 33, 37, 39, 51, 55],
        "treatment_options": ["fongicide_iprodione"],
        "prevention_methods": ["rotation_cultures", "élimination_résidus"],
        "yield_impact": "5-20%"
    },
    {
        "name": "Verticilliose du tournesol",
        "scientific_name": "Verticillium dahliae",
        "common_names": ["Verticillium wilt", "Flétrissement verticillien"],
        "disease_type": "fungal",
        "pathogen_name": "Verticillium dahliae",
        "severity_level": "high",
        "eppo_code": "VERTDA",
        "symptoms": ["flétrissement", "jaunissement_unilatéral", "brunissement_vasculaire"],
        "visual_indicators": ["décoloration_vasculaire", "flétrissement_asymétrique"],
        "favorable_conditions": {"temperature": "moderate", "sol_contaminé": True},
        "seasonal_occurrence": ["été"],
        "susceptible_bbch_stages": [51, 55, 61, 65, 69],
        "treatment_options": ["pas_traitement_curatif"],
        "prevention_methods": ["rotation_longue", "variétés_tolérantes"],
        "yield_impact": "10-50%"
    },
    {
        "name": "Rouille du tournesol",
        "scientific_name": "Puccinia helianthi",
        "common_names": ["Sunflower rust", "Rouille"],
        "disease_type": "fungal",
        "pathogen_name": "Puccinia helianthi",
        "severity_level": "moderate",
        "eppo_code": "PUCCHN",
        "symptoms": ["pustules_brun_rouille", "feuilles_jaunies"],
        "visual_indicators": ["pustules_circulaires", "poudre_rouille"],
        "favorable_conditions": {"humidity": "high", "temperature": "moderate", "temperature_range": [18, 25]},
        "seasonal_occurrence": ["été"],
        "susceptible_bbch_stages": [31, 32, 33, 37, 39, 51, 55, 61],
        "treatment_options": ["fongicide_triazole"],
        "prevention_methods": ["variétés_résistantes"],
        "yield_impact": "5-30%"
    },
    {
        "name": "Botrytis du tournesol",
        "scientific_name": "Botrytis cinerea",
        "common_names": ["Gray mold", "Pourriture grise"],
        "disease_type": "fungal",
        "pathogen_name": "Botrytis cinerea",
        "severity_level": "moderate",
        "eppo_code": "BOTRCI",
        "symptoms": ["pourriture_grise_capitule", "moisissure_grise"],
        "visual_indicators": ["mycélium_gris", "sporulation_grise"],
        "favorable_conditions": {"humidity": "very_high", "temperature": "moderate"},
        "seasonal_occurrence": ["été", "automne"],
        "susceptible_bbch_stages": [61, 65, 69, 71, 75, 83, 85],
        "treatment_options": ["fongicide_iprodione"],
        "prevention_methods": ["aération", "récolte_précoce"],
        "yield_impact": "10-30%"
    },
    {
        "name": "Rhizopus",
        "scientific_name": "Rhizopus stolonifer",
        "common_names": ["Rhizopus head rot", "Pourriture rhizopus"],
        "disease_type": "fungal",
        "pathogen_name": "Rhizopus stolonifer",
        "severity_level": "moderate",
        "eppo_code": "RHIZST",
        "symptoms": ["pourriture_molle_capitule", "mycélium_blanc_gris"],
        "visual_indicators": ["pourriture_rapide", "mycélium_cotonneux"],
        "favorable_conditions": {"humidity": "very_high", "temperature": "warm", "temperature_range": [25, 35]},
        "seasonal_occurrence": ["été", "automne"],
        "susceptible_bbch_stages": [71, 75, 83, 85, 89],
        "treatment_options": ["récolte_précoce", "séchage_rapide"],
        "prevention_methods": ["éviter_blessures", "récolte_maturité_optimale"],
        "yield_impact": "5-25%"
    },
    {
        "name": "Orobanche",
        "scientific_name": "Orobanche cumana",
        "common_names": ["Sunflower broomrape", "Orobanche"],
        "disease_type": "parasitic_plant",
        "pathogen_name": "Orobanche cumana",
        "severity_level": "critical",
        "eppo_code": "OROC",
        "symptoms": ["plantes_parasites", "nanisme", "flétrissement", "jaunissement"],
        "visual_indicators": ["tiges_parasites_émergentes", "fleurs_violettes"],
        "favorable_conditions": {"sol_contaminé": True, "temperature": "warm"},
        "seasonal_occurrence": ["printemps", "été"],
        "susceptible_bbch_stages": [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        "treatment_options": ["herbicide_imazamox"],
        "prevention_methods": ["variétés_résistantes", "rotation_longue", "semences_propres"],
        "yield_impact": "30-100%"
    },
    {
        "name": "Macrophomina",
        "scientific_name": "Macrophomina phaseolina",
        "common_names": ["Charcoal rot", "Pourriture charbonneuse"],
        "disease_type": "fungal",
        "pathogen_name": "Macrophomina phaseolina",
        "severity_level": "high",
        "eppo_code": "MCHPH",
        "symptoms": ["pourriture_racines", "pourriture_tige_base", "verse", "microsclérotes_noirs"],
        "visual_indicators": ["noircissement_tissus", "microsclérotes"],
        "favorable_conditions": {"stress_hydrique": True, "temperature": "hot", "temperature_range": [28, 35]},
        "seasonal_occurrence": ["été"],
        "susceptible_bbch_stages": [51, 55, 61, 65, 69, 71, 75],
        "treatment_options": ["irrigation", "récolte_précoce"],
        "prevention_methods": ["irrigation_régulière", "variétés_tolérantes", "éviter_stress"],
        "yield_impact": "10-50%"
    }
]

